// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my-proto.proto

// Protobuf Java Version: 3.25.1
package proto;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<proto.Person.PhoneNumber> 
      getPhonesList();
  /**
   * <code>repeated .proto.Person.PhoneNumber phones = 4;</code>
   */
  proto.Person.PhoneNumber getPhones(int index);
  /**
   * <code>repeated .proto.Person.PhoneNumber phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .proto.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<? extends proto.Person.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .proto.Person.PhoneNumber phones = 4;</code>
   */
  proto.Person.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);
}
